name: ml
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.13.1
  - beautifulsoup4=4.12.3
  - ipykernel=6.29.5
  - joblib=1.4.2
  - matplotlib=3.10.0
  - numpy=2.2.1
  - pandas=2.2.3
  - plotly=6.0.1
  - requests=2.32.3
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - seaborn=0.13.2
  - statsmodels=0.14.5
  - pip=24.2
  - pip:
      - graphviz==0.21
      - jupyterlab==4.5.0
      - jupyterlab-quarto==0.3.5
      - kagglehub==0.3.13
      - notebook==7.5.0
      - rise==5.7.1
      - tqdm==4.67.1